version: "3.8"
services:
  app-6x:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    volumes:
      - ./core/6x:/work/core
      - ../packages:/work/packages

  app-7x:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    volumes:
      - ./core/7x:/work/core
      - ../packages:/work/packages

  app-8x:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    volumes:
      - ./core/8x:/work/core
      - ../packages:/work/packages

  db-mysql:
    image: mysql:8.0
    ports:
      - 13306:3306
    environment:
      - MYSQL_DATABASE=laravel_local
      - MYSQL_USER=phper
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret

  db-postgres:
    image: postgres:13.1
    ports:
      - 15432:5432
    environment:
      - POSTGRES_DB=laravel_local
      - POSTGRES_USER=phper
      - POSTGRES_PASSWORD=secret
