version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
services:
  app-7x:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./core/7x:/work/core
      - ../packages/7x:/work/packages
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db-mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-laravel_local}
      - DB_USERNAME=${DB_USER:-phper}
      - DB_PASSWORD=${DB_PASS:-secret}

  web-7x:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - 8070:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./core/7x:/work/core

  db-mysql:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - 13306:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel_local}
      - MYSQL_USER=${DB_USER:-phper}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
